project:
  type: book
  render:
    - "index.qmd"
    - "chapters/*.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "_build/"

book:
  title: "R Basics"
  author:
    - "Nick Ulle"
    - "Wesley Brooks"
  date: now
  chapters:
    - "index.qmd"
    - part: "Getting Started"
      chapters:
        - "chapters/getting-started/getting-started.qmd"
        - "chapters/getting-started/working-with-files.qmd"
    - part: "Exploring Data"
      chapters:
        - "chapters/exploring-data/indexing.qmd"
        - "chapters/exploring-data/visualization.qmd"
        - "chapters/exploring-data/grouping.qmd"
    - part: "Data Types & Structures"
      chapters:
        - "chapters/data-types-structures/data-types-structures.qmd"
    - part: "Organizing Code"
      chapters:
        - "chapters/organizing-code/writing-functions.qmd"
        - "chapters/organizing-code/control-flow.qmd"
  appendices:
    - "chapters/appendices/file-systems.qmd"
    - "chapters/appendices/appendix.qmd"
    - "chapters/appendices/where-to-learn-more.qmd"
    - "chapters/appendices/acknowledgements.qmd"
    # - "chapters/appendices/assessment.qmd"
  repo-url: "https://github.com/ucdavisdatalab/workshop_r_basics"
  repo-actions: [issue, source]
  sidebar:
    logo: "images/datalab-logo-full-color-rgb-1.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - text: |
          <style>
          .callout.callout-style-default .callout-body {
            padding: 0 1.5rem 0;
          }
          .cell-output-stdout {
            overflow-y: scroll;
            max-height: 30rem;
            margin-bottom: 0.75rem;
          }
          #quarto-sidebar a.text-start {
            font-variant: small-caps;
          }
          </style>
  pdf: default

execute:
  freeze: auto
